#!/bin/bash

if [ ! -d $1 ] || [ -x $2 ]; then
	echo Usage $0 root_dir output_file
	exit 1
fi

ROOT_DIR=$1
OUTPUT_FILE=$2
TMP_FILE=image.cpio.gz

pushd $ROOT_DIR

find . | cpio -o -H newc | gzip -9 >$TMP_FILE

popd

mv $ROOT_DIR/$TMP_FILE $OUTPUT_FILE
